# Generated by Django 5.0.7 on 2024-11-08 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('end_date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('market_index', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('stock_type', models.CharField(max_length=255)),
                ('stock_code', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('end_date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('beta', models.FloatField(blank=True, null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.market')),
            ],
        ),
    ]
