# Generated by Django 5.0.7 on 2024-11-08 10:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('end_date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('value', models.FloatField(blank=True, null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.market')),
            ],
        ),
    ]
