# Generated by Django 5.0.7 on 2024-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_stock_beta_remove_stock_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beta',
            name='market',
        ),
        migrations.AddField(
            model_name='beta',
            name='market_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
