# Generated by Django 5.0.7 on 2024-11-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_beta_market_beta_market_index_delete_market'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
