# Generated by Django 5.0.7 on 2024-11-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beta',
            name='market_index',
        ),
    ]
