# Generated by Django 5.0.7 on 2024-11-09 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_beta_market_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
